###
GET http://localhost:5000/api/users


# register user
###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "kyrie irving",
    "email": "kyrie@gmail.com",
    "password": "password"
}



# logout user
###
GET http://localhost:5000/api/auth/logout

# check authorization
###
GET http://localhost:5000/api/checkuser

#get profile
###
GET http://localhost:5000/api/auth/profile


# login user
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "kofiarhin@gmail.com",
    "password": "password"
}


# add contact
###
POST http://localhost:5000/api/contacts/add
Content-Type: application/json

{
    "usename": "kyrie Irving",
    "email":"lebron@gmail.com"
}