###
GET http://localhost:5000/api/users


# register user
###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "lebron james",
    "email": "lebron@gmail.com",
    "password": "password"
}

# login user
###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "lebron@gmail.com",
    "password": "password"
}

# logout user
###
GET http://localhost:5000/api/auth/logout

# check authorization
###
GET http://localhost:5000/api/checkuser

#get profile
###
GET http://localhost:5000/api/auth/profile